CREATE TABLE EMPLOYEE(
EMP_ID NUMBER,
EMP_NAME VARCHAR2(50 CHAR),
EMP_PHONE NUMBER,
EMP_EMAIL VARCHAR2(50))
SELECT *from EMPLOYEE

INSERT INTO EMPLOYEE VALUES(
01,'VINEETH',2036062183, 'Vneethkoth@gmail.com')


INSERT INTO EMPLOYEE VALUES
(02,'SUMANTH',2036062184,'Sumanth@gmail.com'),
INSERT INTO EMPLOYEE VALUES
(03,'MOHAN',2036062185,'Mohan@gmail.com'),
INSERT INTO EMPLOYEE VALUES
(04,'IMRAN',2036062186,'Imran@gmail.com');
INSERT INTO EMPLOYEE VALUES
(05,'VACHAN',2036062187,'vachan@gmail.com');
INSERT INTO EMPLOYEE VALUES
(06,'VARUN',2036062188,'Varun@gmail.com');


CREATE TABLE EMP_SAL(
EMP_ID NUMBER,
EMP_SAL NUMBER);
CREATE TABLE EMP_PROJECT(
EMP_ID NUMBER,
Project VARCHAR2(50 CHAR));


INSERT INTO EMP_SAL VALUES(01, 10000);
INSERT INTO EMP_SAL VALUES(02, 15000);
INSERT INTO EMP_SAL VALUES(03, 20000);
INSERT INTO EMP_SAL VALUES(04, 25000);
INSERT INTO EMP_SAL VALUES(05, 30000);
INSERT INTO EMP_SAL VALUES(06, 35000);


INSERT INTO EMP_PROJECT VALUES(01, 'DEVOPS');
INSERT INTO EMP_PROJECT VALUES(02, 'DATA ANYLIST');
INSERT INTO EMP_PROJECT VALUES(03, 'CYBERSECURITY');
INSERT INTO EMP_PROJECT VALUES(04, '.NET DEVELOPER');
INSERT INTO EMP_PROJECT VALUES(05, 'JAVA DEVELOPER');
INSERT INTO EMP_PROJECT VALUES(06, 'JAVA DEVELOPER');


SELECT *
FROM EMPLOYEE INNER JOIN EMP_SAL 
ON EMPLOYEE.EMP_ID = EMP_SAL.EMP_ID
INNER JOIN EMP_PROJECT
ON EMPLOYEE.EMP_ID = EMP_PROJECT.EMP_ID


SELECT EMPLOYEE.EMP_ID, EMPLOYEE.EMP_NAME, EMPLOYEE.EMP_PHONE, EMPLOYEE.EMP_EMAIL, EMP_SAL.EMP_SAL, EMP_PROJECT.PROJECT
FROM EMPLOYEE 
INNER JOIN EMP_SAL 
ON EMPLOYEE.EMP_ID = EMP_SAL.EMP_ID
INNER JOIN EMP_PROJECT
ON EMPLOYEE.EMP_ID = EMP_PROJECT.EMP_ID
