DROP TABLE Projects;
DROP TABLE Users;

CREATE TABLE Users(
user_id NUMBER,
User_Name VARCHAR2 (50 CHAR)UNIQUE,
CONSTRAINT USER_PK PRIMARY KEY(user_id)
);

CREATE TABLE Projects(
project_id NUMBER,
project_name VARCHAR2 (50 CHAR)UNIQUE,
creator VARCHAR2 (50 CHAR) NOT NULL,
CONSTRAINT PROJECTS_PK PRIMARY KEY(project_id),
CONSTRAINT PROJECTS_USERS_FK FOREIGN KEY(creator) REFERENCES Users (User_Name)
ON DELETE CASCADE 
)


INSERT INTO Users VALUES(2,'VINEETH');
INSERT INTO Users VALUES(3, 'MOHAN');
INSERT INTO Users VALUES(4, 'SUMANTH');
INSERT INTO Users VALUES(5, 'SAI');
INSERT INTO Users VALUES(6, 'SHUSANTH');

INSERT INTO Projects VALUES(23, 'PLANNING MANAGEMENT', 'VINEETH');
DELETE FROM Users WHERE user_id = 2
.....
INSERT INTO Users VALUES(2,'VINEETH');

INSERT INTO Users VALUES(3, 'MOHAN');
INSERT INTO Users VALUES(4, 'SUMANTH');
